version: '3.9'

services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 -p 4010 /tmp/openapi.yaml'
    volumes:
      - ./openapi.yaml:/tmp/openapi.yaml:ro
    ports:
      - '4010:4010'
