openapi: 3.1.0
x-stoplight:
  id: u6lcda3q8x2t5
info:
  title: Chef OpenAPI
  version: '1.0'
  description: Chef OpenAPI
  contact:
    name: youichiro
    email: cinnamon416@gmail.com
servers:
  - url: 'http://localhost:4010'
paths:
  /todos:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    data:
                      - id: 1
                        title: todo1
                      - id: 2
                        title: todo2
                      - id: 3
                        title: todo3
                    total: 10
                    isFirst: true
                    isLast: false
                    prevOffset: null
                    nextOffset: 4
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                      required:
                        - id
                        - title
                  total:
                    type: integer
                  isFirst:
                    type: boolean
                  isLast:
                    type: boolean
                  prevOffset:
                    type: 'null'
                  nextOffset:
                    type: integer
                required:
                  - data
                  - total
                  - isFirst
                  - isLast
                  - prevOffset
                  - nextOffset
              examples:
                at_first:
                  value:
                    data:
                      - id: 1
                        title: todo1
                      - id: 2
                        title: todo2
                      - id: 3
                        title: todo3
                    total: 10
                    isFirst: true
                    isLast: false
                    prevOffset: null
                    nextOffset: 4
                at_last:
                  value:
                    data:
                      - id: 10
                        title: todo10
                    total: 10
                    isFirst: false
                    isLast: true
                    prevOffset: 7
                    nextOffset: null
                empty:
                  value:
                    data: []
                    total: 10
                    isFirst: false
                    isLast: true
                    prevOffset: 7
                    nextOffset: null
      operationId: get-todos
      description: GET /todos
      parameters:
        - schema:
            type: number
          in: query
          name: offset
          description: offset
        - schema:
            type: number
          in: query
          name: limit
          description: limit
    parameters: []
  /hello:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    message: hello
                properties:
                  message:
                    type: string
                required:
                  - message
              examples:
                Example 1:
                  value:
                    message: hello
      operationId: get-hello
      description: GET /hello
components:
  schemas: {}
